/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#afc8f0",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#2f486a",
        "tertiary-fixed-dim": "#c4c7c9",
        "background": "#f8f9ff",
        "surface-dim": "#ccdbf3",
        "on-background": "#0d1c2e",
        "surface-variant": "#d5e3fc",
        "primary-fixed": "#d4e3ff",
        "on-tertiary-fixed": "#191c1e",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#eaf1ff",
        "error": "#ba1a1a",
        "inverse-surface": "#233144",
        "tertiary": "#040607",
        "on-surface": "#0d1c2e",
        "outline": "#74777f",
        "surface-container": "#e6eeff",
        "secondary": "#006d37",
        "on-secondary-fixed-variant": "#005228",
        "inverse-primary": "#afc8f0",
        "surface-container-low": "#eff4ff",
        "surface": "#f8f9ff",
        "primary": "#000613",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#6f88ad",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#4ae183",
        "tertiary-container": "#1c1f21",
        "on-secondary": "#ffffff",
        "outline-variant": "#c4c6cf",
        "on-tertiary-container": "#848789",
        "on-secondary-fixed": "#00210c",
        "secondary-fixed": "#6bfe9c",
        "on-secondary-container": "#00743a",
        "secondary-container": "#6bfe9c",
        "tertiary-fixed": "#e0e3e5",
        "error-container": "#ffdad6",
        "on-primary": "#ffffff",
        "on-surface-variant": "#43474e",
        "on-primary-fixed": "#001c3a",
        "primary-container": "#001f3f",
        "surface-tint": "#476083",
        "surface-container-high": "#dce9ff",
        "on-tertiary-fixed-variant": "#444749",
        "surface-container-highest": "#d5e3fc",
        "surface-bright": "#f8f9ff"
      },
      fontFamily: {
        "display-lg": ["Inter"],
        "body-md": ["Inter"],
        "title-lg": ["Inter"],
        "caption": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "label-md": ["Inter"],
        "headline-lg": ["Inter"],
        "body-lg": ["Inter"],
        "headline-md": ["Inter"]
      },
      spacing: {
        "container-max": "1280px",
        "gutter": "24px",
      }
    }
  },
  plugins: [],
}